[2024-02-18T19:05:48.993+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.load_model_task manual__2024-02-18T19:04:40.823306+00:00 [queued]>
[2024-02-18T19:05:49.001+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.load_model_task manual__2024-02-18T19:04:40.823306+00:00 [queued]>
[2024-02-18T19:05:49.002+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-02-18T19:05:49.002+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-02-18T19:05:49.002+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-02-18T19:05:49.012+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_model_task> on 2024-02-18 19:04:40.823306+00:00
[2024-02-18T19:05:49.018+0000] {standard_task_runner.py:55} INFO - Started process 677 to run task
[2024-02-18T19:05:49.021+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'load_model_task', 'manual__2024-02-18T19:04:40.823306+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpwwhfwdop']
[2024-02-18T19:05:49.023+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask load_model_task
[2024-02-18T19:05:49.097+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.load_model_task manual__2024-02-18T19:04:40.823306+00:00 [running]> on host 7aa3f36b0bb4
[2024-02-18T19:05:49.159+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=load_model_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-18T19:04:40.823306+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-18T19:04:40.823306+00:00
[2024-02-18T19:05:49.171+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but KMeans was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

[2024-02-18T19:05:49.208+0000] {python.py:177} INFO - Done. Returned value was: Cluster 9 Number of clusters 8
[2024-02-18T19:05:49.260+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=your_python_dag, task_id=load_model_task, execution_date=20240218T190440, start_date=20240218T190548, end_date=20240218T190549
[2024-02-18T19:05:49.323+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-02-18T19:05:49.338+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
